[macro_parameters]
batch_size = 64
epochs = 1

[model]
name = "AlexNet"
end = 2
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "SGD"
lr = 0.0001

[loss_function]
name = "CrossEntropyLoss"
