[macro_parameters]
batch_size = 64
epochs = 2

[model]
name = "AlexNet"
end = 2
classifier = "./json_modules/alexnet_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.001

[loss_function]
name = "CrossEntropyLoss"
