[macro_parameters]
batch_size = 64
epochs = 1

[model]
name = "densenet_121"
end = 1
classifier = "../json_modules/alexnet_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.01

[loss_function]
name = "CrossEntropyLoss"