[macro_parameters]
batch_size = 32
epochs = 1

[model]
name = "efficientnet_b2"
end = 2
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "AdamW"
lr = 1e-4
weight_decay = 1e-2

[loss_function]
name = "CrossEntropyLoss"
