[macro_parameters]
batch_size = 64
epochs = 1
target_shape = [224, 224]

[model]
name = "googlenet"
end = 3
classifier = "../classifiers/default_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.01

[loss_function]
name = "CrossEntropyLoss"