[macro_parameters]
batch_size = 64
epochs = 15

[model]
name = "mnasnet_1_0"
end = 1
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "RMSprop"
alpha = 0.9
momentum = 0.9
weight_decay = 1e-5

[loss_function]
name = "CrossEntropyLoss"
