[macro_parameters]
batch_size = 128
epochs = 15

[model]
name = "mobileclip_s1"
end = 1
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "AdamW"
lr = 1e-3
weight_decay = 0.005

[loss_function]
name = "CrossEntropyLoss"
