[macro_parameters]
batch_size = 128
epochs = 15

[model]
name = "mobilenet_v3_s"
end = 1
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "RMSprop"
lr = 0.1
momentum = 0.9
weight_decay = 1e-5

[loss_function]
name = "CrossEntropyLoss"
