[macro_parameters]
batch_size = 128
epochs = 1
target_shape = [224, 224]

[model]
name = "shufflenet_v2_1_5"
end = 5
classifier = "../classifiers/default_classifier.json"

[optimizer]
name = "SGD"
learning_rate = 0.01

[loss_function]
name = "CrossEntropyLoss"