[macro_parameters]
batch_size = 128
epochs = 15

[model]
name = "vgg_16"
end = 2
classifier = "./classifiers/default_classifier.json"

[optimizer]
name = "SGD"
lr = 0.01
momentum = 0.9
weight_decay = 5e-4

[loss_function]
name = "CrossEntropyLoss"
